# Generated by Django 4.1 on 2023-04-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvailableQty', models.IntegerField()),
                ('Ingredient', models.TextField()),
                ('Unit', models.TextField()),
                ('PricePerUnit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
