# Generated by Django 4.1 on 2023-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Ingredient',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='AvailableQty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='PricePerUnit',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='Unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
